### ISSUE TITLE
request or assistance

### ISSUE THREAD

**Issue by AronV4** [Nitespring/darkestsouls#2]
Hello I am making a modpack and the enemies of this mod is amazing, but I do not want the rest, I mean minerals, minerals of all kinds in the overworld, etc..
So could you make a mod so that only the enemies are generated with their respective weapons, or if it is possible to modify the mod to change this.

**Comment by Nitespring** [comment]
If you still need help, you can change the loot tables  using a datapack. To disable the ores you need instead to change the "forge.biome_modifier" files for them, always trough a datapack
