### ISSUE TITLE
[Bug] crash on DarkestSouls-Forge1.20.1-v1.0.1.4

### ISSUE THREAD

**Issue by HellXFraud** [Nitespring/darkestsouls#4]
[crash-2024-06-16_16.42.31-client.txt](https://github.com/user-attachments/files/15857360/crash-2024-06-16_16.42.31-client.txt)

**Comment by Nitespring** [comment]
I can't really say much from this

**Comment by Nitespring** [comment]
Should have been fixed in newer versions

**Comment by Nitespring** [comment]
Should be fixed
