### ISSUE TITLE
[1.20.1] Missing textures on every skeleton

### ISSUE THREAD

**Issue by DeshiDesu** [Nitespring/darkestsouls#5]
Forge 47.3.5
geckolib-forge-1.20.1-4.4.7.jar
DarkestSouls-Forge1.20.1-1.2.2.1.jar
![image](https://github.com/user-attachments/assets/fffde23b-17d0-4ff4-ac7c-462d2f5b339a)
![2024-08-01_19 45 34](https://github.com/user-attachments/assets/996f7340-f7e9-4a7c-8ef8-3210e2a4fa1d)
![image](https://github.com/user-attachments/assets/ac3cf026-4be9-4186-a876-d6862938028f)

**Comment by DeshiDesu** [comment]
![image](https://github.com/user-attachments/assets/067b29b5-ae64-4b75-9329-0353aa232a87)
Seems to be a typo issue

**Comment by Nitespring** [comment]
I'll fix
