### ISSUE TITLE
[1.20.1] Broken tags

### ISSUE THREAD

**Issue by DeshiDesu** [Nitespring/darkestsouls#6]
Forge 47.3.5
DarkestSouls-Forge1.20.1-1.2.2.1.jar
The following tags cannot be loaded due to non-existent entries:
```
tags/blocks/bomb_breakable.json
tags/blocks/flame_breakable.json
```
Both these tags contain short_grass which was introduced in 1.20.3 and should be renamed to grass.

```
tags/entity_types/poison_immune.json
tags/items/enchantable/weapon_extended.json
```
Contains tags #minecraft:ignores_poison_and_regen and #minecraft:enchantable/weapon which was introduced in 1.20.5

**Comment by Nitespring** [comment]
I'll fix

**Comment by Nitespring** [comment]
new version is up
