### ISSUE TITLE
animations keep resetting / incompat with Oculus & GeckoLib Compat mod

### ISSUE THREAD

**Issue by thvless** [Nitespring/darkestsouls#7]
using DarkestSouls-Forge1.20.1-1.2.2.4 on forge 47.2.18

geckolib is geckolib-forge-1.20.1-4.4.7 

animations of mobs keep randomly resetting (an example would be going back to t-pose in some games)
![image_23](https://github.com/user-attachments/assets/66887706-1d25-4df1-b904-9a051b11db50)

[latest.log](https://github.com/user-attachments/files/16603124/latest.log)
[modlist.txt](https://github.com/user-attachments/files/16603152/modlist.txt)

**Comment by Nitespring** [comment]
Could be shaders

**Comment by Nitespring** [comment]
Are you using pbr resource pack?

**Comment by Nitespring** [comment]
Ok, I found out the issue I think. Try to remove "OculusGeckolibCompat" or whatever that's called. That's what should be causing the problem

**Comment by thvless** [comment]
Hello, thanks for the quick reply

it's indeed the oculus geck compat mod, closing
